blank_issues_enabled: false
contact_links:
  - name: ğŸ  Alooma Development Homebase
    url: https://rvx.one/alooma-homebase
    about: Access our development homebase for additional information about the repository.
